
remote_theme: just-the-docs/just-the-docs
title: Fluorescence Microscope
description: Open-source fluorescence microscope documentation


# Add a header link to the original GitHub repository
aux_links:
  "View on GitHub":
    - "https://github.com/Alienor134/UC2_Fluorescence_microscope"


defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - INVENTOR
  - STL
  - ControlMotors
  - ControlSerial
  - ControlLight
  - ControlMotors


#just-the-docs:
#  navigation:
#    - title: "Home"
#      url: "/"
#    - title: "Bill of Materials"
#      url: "/bill_of_materials"
#    - title: "Build Instructions"
#      url: "/build"
#    - title: "Usage Example"
#      url: "/automate"

