
remote_theme: just-the-docs/just-the-docs
title: Fluorescence Microscope
description: Open-source fluorescence microscope documentation


defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - INVENTOR
  - STL
  - CSL-Lights
  - CSL-Serial
  - CSL-camera
  - Motorized-stage


#just-the-docs:
#  navigation:
#    - title: "Home"
#      url: "/"
#    - title: "Bill of Materials"
#      url: "/bill_of_materials"
#    - title: "Build Instructions"
#      url: "/build"
#    - title: "Usage Example"
#      url: "/automate"

