theme: minimal
title: Fluorescence Microscope
description: Open-source fluorescence microscope documentation

minimal:
  navigation:
    - title: "Home"
      url: "/"
    - title: "Bill of Materials"
      url: "/bill_of_materials"
    - title: "Build Instructions"
      url: "/build"
    - title: "Usage Example"
      url: "/automate"

