
remote_theme: just-the-docs/just-the-docs
title: Fluorescence Microscope
description: Open-source fluorescence microscope documentation

just-the-docs:
  navigation:
    - title: "Home"
      url: "/"
    - title: "Bill of Materials"
      url: "/bill_of_materials"
    - title: "Build Instructions"
      url: "/build"
    - title: "Usage Example"
      url: "/automate"

